---

- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap '
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Install Kubernetes packages.
  package:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  notify: restart kubelet
  with_items: "{{ kube_packages }}"

- name: Create /etc/modules-load.d/k8s.conf if it doesn't exist
  file:
    path: /etc/modules-load.d/k8s.conf
    state: touch

- name: Add kernel modules to /etc/modules-load.d/k8s.conf
  lineinfile:
      path: /etc/modules-load.d/k8s.conf
      line: "{{ item }}"
  with_items:
      - "overlay"
      - "br_netfilter"

- name: Load overlay kernel module
  modprobe:
      name: overlay

- name: Load br_netfilter kernel module
  modprobe:
      name: br_netfilter

- name: Create /etc/sysctl.d/k8s.conf if it doesn't exist
  file:
    path: /etc/sysctl.d/k8s.conf
    state: touch
        
- name: Set sysctl parameters
  lineinfile:
      path: /etc/sysctl.d/k8s.conf
      line: "{{ item }}"
  with_items:
      - "net.bridge.bridge-nf-call-iptables = 1"
      - "net.bridge.bridge-nf-call-ip6tables = 1"
      - "net.ipv4.ip_forward = 1"

- name: Apply sysctl settings
  command: sysctl --system

- name: Download GPG key from URL
  get_url:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      dest: /tmp/apt-key.gpg

- name: Add GPG key to apt-key
  apt_key:
      keyring: /etc/apt/trusted.gpg.d/google-cloud.gpg
      id: /tmp/apt-key.gpg

- name: Add Kubernetes repository
      apt_repository:
        repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
        state: present      