---
- hosts: master
  gather_facts: false
  become: yes
  
  tasks:
  # - name: Initialize Kubernetes control plane with kubeadm init
  #   command: >
  #     kubeadm init
  #     --pod-network-cidr=10.244.0.0/16

  # - name: Ensure .kube directory exists.
  #   file:
  #     path: ~/.kube
  #     state: directory
  #     mode: 0755

  # - name: Symlink the kubectl admin.conf to ~/.kube/conf.
  #   file:
  #     src: /etc/kubernetes/admin.conf
  #     dest: ~/.kube/config
  #     state: link
  #     mode: 0644

  # - name: Configure Flannel networking.
  #   command: >
  #     kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml

  - name: Get the kubeadm join command from the Kubernetes control plane.
    command: kubeadm token create --print-join-command
    changed_when: false
    register: kubernetes_join_command

  - name: join command output  
    debug:
      msg:
      - "{{ kubernetes_join_command.stdout_lines[0] }}"

  - name: Copy join command to local file.
    become: yes
    local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

- hosts: worker
  gather_facts: false
  become: yes

  tasks:
  - name: Copy join command from Ansiblehost to the worker nodes.
    become: yes
    copy:
      src: /tmp/kubernetes_join_command
      dest: /tmp/kubernetes_join_command
      mode: 0777

  - name: Join the Worker nodes to the cluster.
    become: yes
    command: sh /tmp/kubernetes_join_command
    register: joined_or_not